/**
 * CA-19 — the demo workbook's proposal, pinned by exact expectation (F02 CA-16
 * precedent). Every table, field, type, enum option, key, label, relationship
 * (with its source, candidates and broken-reference count), classification,
 * inert count and statement — subject, edit, evidence kinds, disposition and
 * the exact fingerprint **input** — for `fieldwork-q3.xlsx` with every sheet
 * selected, and with `Archive 2018` deselected. Any change to the demo
 * workbook, the OOXML adapter or inference that moves one of these is a CA-19
 * change S06/S07 must hear about.
 */

import { describe, expect, it } from "vitest";
import { DEMO, proposeFixture } from "./demo-harness.js";
import { pinOf } from "./pin-projection.js";

const ALL_SHEETS = {
  appName: "Fieldwork Q3",
  isDelimited: false,
  sheets: [
    ["s0", "Jobs", true, ["table"]],
    ["s1", "Customers", true, ["table"]],
    ["s2", "Crew", true, ["table"]],
    ["s3", "Visits", true, ["table"]],
    ["s4", "Materials", true, ["table", "lookup"]],
    ["s5", "Overview", true, ["summary", "chart"]],
    ["s6", "Archive 2018", true, ["table"]],
  ],
  tables: [
    {
      tableKey: "s0.t0",
      tableName: "Jobs",
      source: "declared-table",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 60,
      discardedRowCount: 0,
      key: "s0.t0.c0",
      label: "s0.t0.c0",
      fields: [
        ["s0.t0.c0", "Job ID", "text", "text", "text", [], 0, null],
        ["s0.t0.c1", "Customer ID", "reference", "text", "text", [], 0, null],
        ["s0.t0.c2", "Customer", "text", "text", "text", [], 0, "VLOOKUP(B2,Customers!A:B,2,FALSE)"],
        [
          "s0.t0.c3",
          "Status",
          "enum",
          "enum",
          "enum",
          ["Scheduled", "In progress", "Waiting", "Complete"],
          0,
          null,
        ],
        ["s0.t0.c4", "Quoted amount", "currency:USD", "currency:USD", "decimal:", [], 2, null],
        ["s0.t0.c5", "Paid", "currency:USD", "currency:USD", "decimal:", [], 0, null],
        ["s0.t0.c6", "Balance", "currency:USD", "currency:USD", "decimal:", [], 2, "E2-F2"],
        ["s0.t0.c7", "Due date", "date", "date", "serial-date:1900", [], 0, null],
        ["s0.t0.c8", "Approved", "boolean", "boolean", "boolean", [], 0, null],
        [
          "s0.t0.c9",
          "Material",
          "enum",
          "enum",
          "enum",
          ["Gravel", "Sand", "Topsoil", "Mulch", "Pavers", "Timber", "Fencing", "Seed mix"],
          0,
          null,
        ],
      ],
    },
    {
      tableKey: "s1.t0",
      tableName: "Customers",
      source: "declared-table",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 12,
      discardedRowCount: 0,
      key: "s1.t0.c0",
      label: "s1.t0.c1",
      fields: [
        ["s1.t0.c0", "Customer ID", "text", "text", "text", [], 0, null],
        ["s1.t0.c1", "Name", "text", "text", "text", [], 0, null],
        ["s1.t0.c2", "Phone", "phone", "phone", "text", [], 0, null],
        ["s1.t0.c3", "Email", "email", "email", "text", [], 0, null],
      ],
    },
    {
      tableKey: "s2.r0",
      tableName: "Crew",
      source: "region",
      joinedTo: null,
      headerRowIndex: 3,
      rowCount: 24,
      discardedRowCount: 3,
      key: null,
      label: "s2.r0.c0",
      fields: [
        ["s2.r0.c0", "Name", "text", "text", "text", [], 0, null],
        ["s2.r0.c1", "Role", "enum", "enum", "enum", ["Apprentice", "Driver", "Lead", "Technician"], 0, null],
        ["s2.r0.c2", "Phone", "phone", "phone", "text", [], 0, null],
        ["s2.r0.c3", "Crew", "enum", "enum", "enum", ["East", "North", "South", "West"], 0, null],
      ],
    },
    {
      tableKey: "s2.r1",
      tableName: "Crew 2",
      source: "region",
      joinedTo: "s2.r0",
      headerRowIndex: 29,
      rowCount: 10,
      discardedRowCount: 0,
      key: null,
      label: "s2.r1.c0",
      fields: [
        ["s2.r1.c0", "Name", "text", "text", "text", [], 0, null],
        ["s2.r1.c1", "Role", "enum", "enum", "enum", ["Apprentice", "Driver", "Lead", "Technician"], 0, null],
        ["s2.r1.c2", "Phone", "phone", "phone", "text", [], 0, null],
        ["s2.r1.c3", "Crew", "enum", "enum", "enum", ["East", "North", "South", "West"], 0, null],
      ],
    },
    {
      tableKey: "s3.t0",
      tableName: "Visits",
      source: "declared-table",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 40,
      discardedRowCount: 0,
      key: "s3.t0.c0",
      label: "s3.t0.c0",
      fields: [
        ["s3.t0.c0", "Visit ID", "text", "text", "text", [], 0, null],
        ["s3.t0.c1", "Job ID", "reference", "text", "text", [], 0, null],
        ["s3.t0.c2", "Visit date", "date", "date", "serial-date:1900", [], 0, null],
        [
          "s3.t0.c3",
          "Notes",
          "enum",
          "enum",
          "enum",
          ["Follow-up booked", "Gate code needed", "Measured site"],
          0,
          null,
        ],
      ],
    },
    {
      tableKey: "s4.r0",
      tableName: "Materials",
      source: "region",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 8,
      discardedRowCount: 0,
      key: null,
      label: "s4.r0.c0",
      fields: [["s4.r0.c0", "Material", "text", "text", "text", [], 0, null]],
    },
    {
      tableKey: "s6.r0",
      tableName: "Archive 2018",
      source: "region",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 2000,
      discardedRowCount: 0,
      key: "s6.r0.c0",
      label: "s6.r0.c0",
      fields: [
        ["s6.r0.c0", "Job ID", "text", "text", "text", [], 0, null],
        [
          "s6.r0.c1",
          "Customer",
          "enum",
          "enum",
          "enum",
          ["Alder Court HOA", "Bramble Yard Ltd", "Cedar Mill Co-op", "Dunmore Lot Trust", "Elm Street Clinic", "Fernhill School", "Garnet Properties", "Harbor View Inn", "Ivy Lane Bakery", "Juniper Farms", "Kestrel Storage", "Linden Library"],
          0,
          null,
        ],
        ["s6.r0.c2", "Amount", "currency:USD", "currency:USD", "decimal:", [], 0, null],
        ["s6.r0.c3", "Closed", "date", "date", "serial-date:1900", [], 0, null],
      ],
    },
  ],
  relationships: [
    {
      relationshipKey: "rel:s0.t0.c1",
      fromTableKey: "s0.t0",
      fromColumnKey: "s0.t0.c1",
      toTableKey: "s1.t0",
      toColumnKey: "s1.t0.c0",
      detectionSource: "lookup-formula",
      isApplied: true,
      brokenReferenceCount: 1,
      isSampled: false,
      candidates: [{ toTableKey: "s1.t0", toColumnKey: "s1.t0.c0", basis: "lookup-formula", brokenReferenceCount: 1 }],
    },
    {
      relationshipKey: "rel:s3.t0.c1",
      fromTableKey: "s3.t0",
      fromColumnKey: "s3.t0.c1",
      toTableKey: "s0.t0",
      toColumnKey: "s0.t0.c0",
      detectionSource: "key-match",
      isApplied: true,
      brokenReferenceCount: 0,
      isSampled: false,
      candidates: [
        {
          toTableKey: "s0.t0",
          toColumnKey: "s0.t0.c0",
          basis: "heading-and-containment",
          brokenReferenceCount: 0,
        },
        { toTableKey: "s6.r0", toColumnKey: "s6.r0.c0", basis: "heading", brokenReferenceCount: 40 },
      ],
    },
  ],
  recordRules: [],
  // F04 (S07): the demo's formulas, live. Jobs Balance and the Customer lookup
  // (through the Customer ID relationship) become computed columns; the four
  // Overview formulas become dashboard values, Balance reading the two SUMs.
  formulas: [
    ["s0.t0.c2", "computed-column", null, "VLOOKUP(B2,Customers!A:B,2,FALSE)", "Jobs!C2:C61", 60, "live", "deterministic", null, "rel:s0.t0.c1", true],
    ["s0.t0.c6", "computed-column", null, "E2-F2", "Jobs!G2:G61", 60, "live", "deterministic", null, null, true],
    ["s5.R3C2", "dashboard-value", "Open jobs", 'COUNTIF(Jobs!D2:D61,"In progress")', "Overview!B3", 1, "live", "deterministic", null, null, true],
    ["s5.R4C2", "dashboard-value", "Quoted total", "SUM(Jobs!E2:E61)", "Overview!B4", 1, "live", "deterministic", null, null, true],
    ["s5.R5C2", "dashboard-value", "Paid total", "SUM(Jobs!F2:F61)", "Overview!B5", 1, "live", "deterministic", null, null, true],
    ["s5.R6C2", "dashboard-value", "Balance", "B4-B5", "Overview!B6", 1, "live", "deterministic", null, null, true],
  ],
  // F04: formulas now live — the three formula items (two columns, the Overview cells) are gone.
  inertCounts: { chart: 1, drawing: 2, "cell-styling": 7 },
  statements: [
    [
      "app-name",
      "app-name",
      "rename-app",
      ["file-name"],
      "accepted",
      "[\"sheaf.inference.v2\",\"app-name\",\"file-name\",\"fieldwork-q3.xlsx\"]",
    ],
    [
      "table-name:s0.t0",
      "table-name",
      "rename-table",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Jobs\",\"JobsTable\",\"declared-table\",\"JobsTable\"]",
    ],
    [
      "header-row:s0.t0",
      "header-row",
      "set-header-row",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Jobs\",\"JobsTable\",\"declared-table\",\"JobsTable\"]",
    ],
    [
      "table-key:s0.t0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Jobs\",\"JobsTable\",\"header-text\",\"Job ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s0.t0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Jobs\",\"JobsTable\",\"header-text\",\"Job ID\",\"distinct-values\"]",
    ],
    [
      "field-name:s0.t0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",0,\"header-text\",\"Job ID\"]",
    ],
    [
      "field-type:s0.t0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",0]",
    ],
    [
      "field-name:s0.t0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",1,\"header-text\",\"Customer ID\"]",
    ],
    [
      "field-type:s0.t0.c1",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",1]",
    ],
    [
      "field-name:s0.t0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",2,\"header-text\",\"Customer\"]",
    ],
    [
      "field-type:s0.t0.c2",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",2]",
    ],
    [
      "formula:s0.t0.c2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Jobs\",\"JobsTable\",2,\"formula-text\",\"VLOOKUP(B2,Customers!A:B,2,FALSE)\"]",
    ],
    [
      "field-name:s0.t0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",3,\"header-text\",\"Status\"]",
    ],
    [
      "field-type:s0.t0.c3",
      "field-type",
      "override-type",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",3,\"validation-rule\",\"list\",\"\",\"Scheduled\",\"In progress\",\"Waiting\",\"Complete\",\"\\\"Scheduled,In progress,Waiting,Complete\\\"\",\"\"]",
    ],
    [
      "enum-options:s0.t0.c3",
      "enum-options",
      "edit-enum-options",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Jobs\",\"JobsTable\",3,\"validation-rule\",\"list\",\"\",\"Scheduled\",\"In progress\",\"Waiting\",\"Complete\",\"\\\"Scheduled,In progress,Waiting,Complete\\\"\",\"\"]",
    ],
    [
      "field-name:s0.t0.c4",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",4,\"header-text\",\"Quoted amount\"]",
    ],
    [
      "field-type:s0.t0.c4",
      "field-type",
      "override-type",
      ["number-format", "value-conflict"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",4,\"number-format\",\"\\\"$\\\"#,##0.00\",\"value-conflict\"]",
    ],
    [
      "field-name:s0.t0.c5",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",5,\"header-text\",\"Paid\"]",
    ],
    [
      "field-type:s0.t0.c5",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",5,\"number-format\",\"\\\"$\\\"#,##0.00\"]",
    ],
    [
      "field-name:s0.t0.c6",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",6,\"header-text\",\"Balance\"]",
    ],
    [
      "field-type:s0.t0.c6",
      "field-type",
      "override-type",
      ["number-format", "value-conflict"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",6,\"number-format\",\"\\\"$\\\"#,##0.00\",\"value-conflict\"]",
    ],
    [
      "formula:s0.t0.c6",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Jobs\",\"JobsTable\",6,\"formula-text\",\"E2-F2\"]",
    ],
    [
      "field-name:s0.t0.c7",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",7,\"header-text\",\"Due date\"]",
    ],
    [
      "field-type:s0.t0.c7",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",7,\"number-format\",\"yyyy-mm-dd\"]",
    ],
    [
      "field-name:s0.t0.c8",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",8,\"header-text\",\"Approved\"]",
    ],
    [
      "field-type:s0.t0.c8",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",8,\"value-pattern\",\"boolean-word\",\"\"]",
    ],
    [
      "field-name:s0.t0.c9",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",9,\"header-text\",\"Material\"]",
    ],
    [
      "field-type:s0.t0.c9",
      "field-type",
      "override-type",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",9,\"validation-rule\",\"list\",\"\",\"Materials!$A$2:$A$9\",\"Materials!$A$2:$A$9\",\"\"]",
    ],
    [
      "enum-options:s0.t0.c9",
      "enum-options",
      "edit-enum-options",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Jobs\",\"JobsTable\",9,\"validation-rule\",\"list\",\"\",\"Materials!$A$2:$A$9\",\"Materials!$A$2:$A$9\",\"\"]",
    ],
    [
      "table-name:s1.t0",
      "table-name",
      "rename-table",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Customers\",\"CustomersTable\",\"declared-table\",\"CustomersTable\"]",
    ],
    [
      "header-row:s1.t0",
      "header-row",
      "set-header-row",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Customers\",\"CustomersTable\",\"declared-table\",\"CustomersTable\"]",
    ],
    [
      "table-key:s1.t0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Customers\",\"CustomersTable\",\"header-text\",\"Customer ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s1.t0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Customers\",\"CustomersTable\",\"header-text\",\"Name\",\"distinct-values\"]",
    ],
    [
      "field-name:s1.t0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",0,\"header-text\",\"Customer ID\"]",
    ],
    [
      "field-type:s1.t0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",0]",
    ],
    [
      "field-name:s1.t0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",1,\"header-text\",\"Name\"]",
    ],
    [
      "field-type:s1.t0.c1",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",1]",
    ],
    [
      "field-name:s1.t0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",2,\"header-text\",\"Phone\"]",
    ],
    [
      "field-type:s1.t0.c2",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",2,\"value-pattern\",\"telephone-number\",\"\"]",
    ],
    [
      "field-name:s1.t0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",3,\"header-text\",\"Email\"]",
    ],
    [
      "field-type:s1.t0.c3",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",3,\"value-pattern\",\"email-address\",\"\"]",
    ],
    [
      "table-name:s2.r0",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Crew\",\"r0\",\"sheet-shape\",\"Crew\"]",
    ],
    [
      "header-row:s2.r0",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Crew\",\"r0\",\"header-text\",\"Name · Role · Phone · Crew\"]",
    ],
    [
      "discarded-rows:s2.r0",
      "discarded-rows",
      "set-header-row",
      ["row-shape", "row-shape", "row-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"discarded-rows\",\"Crew\",\"r0\",\"row-shape\",\"row-shape\",\"row-shape\"]",
    ],
    [
      "table-key:s2.r0",
      "table-key",
      "set-key",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Crew\",\"r0\"]",
    ],
    [
      "table-label:s2.r0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Crew\",\"r0\",\"header-text\",\"Name\",\"distinct-values\"]",
    ],
    [
      "field-name:s2.r0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",0,\"header-text\",\"Name\"]",
    ],
    [
      "field-type:s2.r0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",0]",
    ],
    [
      "field-name:s2.r0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",1,\"header-text\",\"Role\"]",
    ],
    [
      "field-type:s2.r0.c1",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "enum-options:s2.r0.c1",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r0\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "field-name:s2.r0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",2,\"header-text\",\"Phone\"]",
    ],
    [
      "field-type:s2.r0.c2",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",2,\"value-pattern\",\"telephone-number\",\"\"]",
    ],
    [
      "field-name:s2.r0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",3,\"header-text\",\"Crew\"]",
    ],
    [
      "field-type:s2.r0.c3",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "enum-options:s2.r0.c3",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r0\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "table-name:s2.r1",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Crew\",\"r1\",\"sheet-shape\",\"Crew\"]",
    ],
    [
      "header-row:s2.r1",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Crew\",\"r1\",\"header-text\",\"Name · Role · Phone · Crew\"]",
    ],
    [
      "table-merge:s2.r1",
      "table-merge",
      "reject-statement",
      ["matching-headings"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-merge\",\"Crew\",\"r1\",\"matching-headings\",\"Name\",\"Role\",\"Phone\",\"Crew\"]",
    ],
    [
      "table-key:s2.r1",
      "table-key",
      "set-key",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Crew\",\"r1\"]",
    ],
    [
      "table-label:s2.r1",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Crew\",\"r1\",\"header-text\",\"Name\",\"distinct-values\"]",
    ],
    [
      "field-name:s2.r1.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",0,\"header-text\",\"Name\"]",
    ],
    [
      "field-type:s2.r1.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",0]",
    ],
    [
      "field-name:s2.r1.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",1,\"header-text\",\"Role\"]",
    ],
    [
      "field-type:s2.r1.c1",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "enum-options:s2.r1.c1",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r1\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "field-name:s2.r1.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",2,\"header-text\",\"Phone\"]",
    ],
    [
      "field-type:s2.r1.c2",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",2,\"value-pattern\",\"telephone-number\",\"\"]",
    ],
    [
      "field-name:s2.r1.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",3,\"header-text\",\"Crew\"]",
    ],
    [
      "field-type:s2.r1.c3",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "enum-options:s2.r1.c3",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r1\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "table-name:s3.t0",
      "table-name",
      "rename-table",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Visits\",\"VisitsTable\",\"declared-table\",\"VisitsTable\"]",
    ],
    [
      "header-row:s3.t0",
      "header-row",
      "set-header-row",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Visits\",\"VisitsTable\",\"declared-table\",\"VisitsTable\"]",
    ],
    [
      "table-key:s3.t0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Visits\",\"VisitsTable\",\"header-text\",\"Visit ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s3.t0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Visits\",\"VisitsTable\",\"header-text\",\"Visit ID\",\"distinct-values\"]",
    ],
    [
      "field-name:s3.t0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",0,\"header-text\",\"Visit ID\"]",
    ],
    [
      "field-type:s3.t0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",0]",
    ],
    [
      "field-name:s3.t0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",1,\"header-text\",\"Job ID\"]",
    ],
    [
      "field-type:s3.t0.c1",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",1]",
    ],
    [
      "field-name:s3.t0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",2,\"header-text\",\"Visit date\"]",
    ],
    [
      "field-type:s3.t0.c2",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",2,\"number-format\",\"yyyy-mm-dd\"]",
    ],
    [
      "field-name:s3.t0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",3,\"header-text\",\"Notes\"]",
    ],
    [
      "field-type:s3.t0.c3",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",3,\"distinct-values\",\"Follow-up booked\",\"Gate code needed\",\"Measured site\"]",
    ],
    [
      "enum-options:s3.t0.c3",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Visits\",\"VisitsTable\",3,\"distinct-values\",\"Follow-up booked\",\"Gate code needed\",\"Measured site\"]",
    ],
    [
      "sheet-classification:s4.lookup",
      "sheet-classification",
      "reject-statement",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"sheet-classification\",\"Materials\",\"lookup\",\"validation-rule\",\"list\",\"\",\"Materials!$A$2:$A$9\",\"Materials!$A$2:$A$9\",\"\"]",
    ],
    [
      "table-name:s4.r0",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Materials\",\"r0\",\"sheet-shape\",\"Materials\"]",
    ],
    [
      "header-row:s4.r0",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Materials\",\"r0\",\"header-text\",\"Material\"]",
    ],
    [
      "table-key:s4.r0",
      "table-key",
      "set-key",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Materials\",\"r0\"]",
    ],
    [
      "table-label:s4.r0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Materials\",\"r0\",\"header-text\",\"Material\",\"distinct-values\"]",
    ],
    [
      "field-name:s4.r0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Materials\",\"r0\",0,\"header-text\",\"Material\"]",
    ],
    [
      "field-type:s4.r0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Materials\",\"r0\",0]",
    ],
    [
      "sheet-classification:s5.summary",
      "sheet-classification",
      "reject-statement",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"sheet-classification\",\"Overview\",\"summary\",\"sheet-shape\",\"Overview\"]",
    ],
    [
      "sheet-classification:s5.chart",
      "sheet-classification",
      "reject-statement",
      ["preserved-part"],
      "accepted",
      "[\"sheaf.inference.v2\",\"sheet-classification\",\"Overview\",\"chart\",\"preserved-part\",\"chart\"]",
    ],
    // F04: the Overview summary formulas are dashboard values now, each its own statement.
    [
      "formula:s5.R3C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R3C2\",\"formula-text\",\"COUNTIF(Jobs!D2:D61,\\\"In progress\\\")\"]",
    ],
    [
      "formula:s5.R4C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R4C2\",\"formula-text\",\"SUM(Jobs!E2:E61)\"]",
    ],
    [
      "formula:s5.R5C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R5C2\",\"formula-text\",\"SUM(Jobs!F2:F61)\"]",
    ],
    [
      "formula:s5.R6C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R6C2\",\"formula-text\",\"B4-B5\"]",
    ],
    [
      "table-name:s6.r0",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Archive 2018\",\"r0\",\"sheet-shape\",\"Archive 2018\"]",
    ],
    [
      "header-row:s6.r0",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Archive 2018\",\"r0\",\"header-text\",\"Job ID · Customer · Amount · Closed\"]",
    ],
    [
      "table-key:s6.r0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Archive 2018\",\"r0\",\"header-text\",\"Job ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s6.r0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Archive 2018\",\"r0\",\"header-text\",\"Job ID\",\"distinct-values\"]",
    ],
    [
      "field-name:s6.r0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Archive 2018\",\"r0\",0,\"header-text\",\"Job ID\"]",
    ],
    [
      "field-type:s6.r0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Archive 2018\",\"r0\",0]",
    ],
    [
      "field-name:s6.r0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Archive 2018\",\"r0\",1,\"header-text\",\"Customer\"]",
    ],
    [
      "field-type:s6.r0.c1",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Archive 2018\",\"r0\",1,\"distinct-values\",\"Alder Court HOA\",\"Bramble Yard Ltd\",\"Cedar Mill Co-op\",\"Dunmore Lot Trust\",\"Elm Street Clinic\",\"Fernhill School\",\"Garnet Properties\",\"Harbor View Inn\",\"Ivy Lane Bakery\",\"Juniper Farms\",\"Kestrel Storage\",\"Linden Library\"]",
    ],
    [
      "enum-options:s6.r0.c1",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Archive 2018\",\"r0\",1,\"distinct-values\",\"Alder Court HOA\",\"Bramble Yard Ltd\",\"Cedar Mill Co-op\",\"Dunmore Lot Trust\",\"Elm Street Clinic\",\"Fernhill School\",\"Garnet Properties\",\"Harbor View Inn\",\"Ivy Lane Bakery\",\"Juniper Farms\",\"Kestrel Storage\",\"Linden Library\"]",
    ],
    [
      "field-name:s6.r0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Archive 2018\",\"r0\",2,\"header-text\",\"Amount\"]",
    ],
    [
      "field-type:s6.r0.c2",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Archive 2018\",\"r0\",2,\"number-format\",\"\\\"$\\\"#,##0.00\"]",
    ],
    [
      "field-name:s6.r0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Archive 2018\",\"r0\",3,\"header-text\",\"Closed\"]",
    ],
    [
      "field-type:s6.r0.c3",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Archive 2018\",\"r0\",3,\"number-format\",\"yyyy-mm-dd\"]",
    ],
    [
      "relationship:rel:s0.t0.c1",
      "relationship",
      "reject-relationship",
      ["lookup-formula"],
      "accepted",
      "[\"sheaf.inference.v2\",\"relationship\",\"Jobs\",\"JobsTable\",1,\"lookup-formula\",\"VLOOKUP\",\"Customers\",\"Customer ID\",\"relationship\"]",
    ],
    [
      "relationship:rel:s3.t0.c1",
      "relationship",
      "reject-relationship",
      ["key-match"],
      "accepted",
      "[\"sheaf.inference.v2\",\"relationship\",\"Visits\",\"VisitsTable\",1,\"key-match\",\"Jobs\",\"Job ID\"]",
    ],
  ],
};

const ARCHIVE_DESELECTED = {
  appName: "Fieldwork Q3",
  isDelimited: false,
  sheets: [
    ["s0", "Jobs", true, ["table"]],
    ["s1", "Customers", true, ["table"]],
    ["s2", "Crew", true, ["table"]],
    ["s3", "Visits", true, ["table"]],
    ["s4", "Materials", true, ["table", "lookup"]],
    ["s5", "Overview", true, ["summary", "chart"]],
    ["s6", "Archive 2018", false, ["excluded"]],
  ],
  tables: [
    {
      tableKey: "s0.t0",
      tableName: "Jobs",
      source: "declared-table",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 60,
      discardedRowCount: 0,
      key: "s0.t0.c0",
      label: "s0.t0.c0",
      fields: [
        ["s0.t0.c0", "Job ID", "text", "text", "text", [], 0, null],
        ["s0.t0.c1", "Customer ID", "reference", "text", "text", [], 0, null],
        ["s0.t0.c2", "Customer", "text", "text", "text", [], 0, "VLOOKUP(B2,Customers!A:B,2,FALSE)"],
        [
          "s0.t0.c3",
          "Status",
          "enum",
          "enum",
          "enum",
          ["Scheduled", "In progress", "Waiting", "Complete"],
          0,
          null,
        ],
        ["s0.t0.c4", "Quoted amount", "currency:USD", "currency:USD", "decimal:", [], 2, null],
        ["s0.t0.c5", "Paid", "currency:USD", "currency:USD", "decimal:", [], 0, null],
        ["s0.t0.c6", "Balance", "currency:USD", "currency:USD", "decimal:", [], 2, "E2-F2"],
        ["s0.t0.c7", "Due date", "date", "date", "serial-date:1900", [], 0, null],
        ["s0.t0.c8", "Approved", "boolean", "boolean", "boolean", [], 0, null],
        [
          "s0.t0.c9",
          "Material",
          "enum",
          "enum",
          "enum",
          ["Gravel", "Sand", "Topsoil", "Mulch", "Pavers", "Timber", "Fencing", "Seed mix"],
          0,
          null,
        ],
      ],
    },
    {
      tableKey: "s1.t0",
      tableName: "Customers",
      source: "declared-table",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 12,
      discardedRowCount: 0,
      key: "s1.t0.c0",
      label: "s1.t0.c1",
      fields: [
        ["s1.t0.c0", "Customer ID", "text", "text", "text", [], 0, null],
        ["s1.t0.c1", "Name", "text", "text", "text", [], 0, null],
        ["s1.t0.c2", "Phone", "phone", "phone", "text", [], 0, null],
        ["s1.t0.c3", "Email", "email", "email", "text", [], 0, null],
      ],
    },
    {
      tableKey: "s2.r0",
      tableName: "Crew",
      source: "region",
      joinedTo: null,
      headerRowIndex: 3,
      rowCount: 24,
      discardedRowCount: 3,
      key: null,
      label: "s2.r0.c0",
      fields: [
        ["s2.r0.c0", "Name", "text", "text", "text", [], 0, null],
        ["s2.r0.c1", "Role", "enum", "enum", "enum", ["Apprentice", "Driver", "Lead", "Technician"], 0, null],
        ["s2.r0.c2", "Phone", "phone", "phone", "text", [], 0, null],
        ["s2.r0.c3", "Crew", "enum", "enum", "enum", ["East", "North", "South", "West"], 0, null],
      ],
    },
    {
      tableKey: "s2.r1",
      tableName: "Crew 2",
      source: "region",
      joinedTo: "s2.r0",
      headerRowIndex: 29,
      rowCount: 10,
      discardedRowCount: 0,
      key: null,
      label: "s2.r1.c0",
      fields: [
        ["s2.r1.c0", "Name", "text", "text", "text", [], 0, null],
        ["s2.r1.c1", "Role", "enum", "enum", "enum", ["Apprentice", "Driver", "Lead", "Technician"], 0, null],
        ["s2.r1.c2", "Phone", "phone", "phone", "text", [], 0, null],
        ["s2.r1.c3", "Crew", "enum", "enum", "enum", ["East", "North", "South", "West"], 0, null],
      ],
    },
    {
      tableKey: "s3.t0",
      tableName: "Visits",
      source: "declared-table",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 40,
      discardedRowCount: 0,
      key: "s3.t0.c0",
      label: "s3.t0.c0",
      fields: [
        ["s3.t0.c0", "Visit ID", "text", "text", "text", [], 0, null],
        ["s3.t0.c1", "Job ID", "reference", "text", "text", [], 0, null],
        ["s3.t0.c2", "Visit date", "date", "date", "serial-date:1900", [], 0, null],
        [
          "s3.t0.c3",
          "Notes",
          "enum",
          "enum",
          "enum",
          ["Follow-up booked", "Gate code needed", "Measured site"],
          0,
          null,
        ],
      ],
    },
    {
      tableKey: "s4.r0",
      tableName: "Materials",
      source: "region",
      joinedTo: null,
      headerRowIndex: 0,
      rowCount: 8,
      discardedRowCount: 0,
      key: null,
      label: "s4.r0.c0",
      fields: [["s4.r0.c0", "Material", "text", "text", "text", [], 0, null]],
    },
  ],
  relationships: [
    {
      relationshipKey: "rel:s0.t0.c1",
      fromTableKey: "s0.t0",
      fromColumnKey: "s0.t0.c1",
      toTableKey: "s1.t0",
      toColumnKey: "s1.t0.c0",
      detectionSource: "lookup-formula",
      isApplied: true,
      brokenReferenceCount: 1,
      isSampled: false,
      candidates: [{ toTableKey: "s1.t0", toColumnKey: "s1.t0.c0", basis: "lookup-formula", brokenReferenceCount: 1 }],
    },
    {
      relationshipKey: "rel:s3.t0.c1",
      fromTableKey: "s3.t0",
      fromColumnKey: "s3.t0.c1",
      toTableKey: "s0.t0",
      toColumnKey: "s0.t0.c0",
      detectionSource: "key-match",
      isApplied: true,
      brokenReferenceCount: 0,
      isSampled: false,
      candidates: [
        {
          toTableKey: "s0.t0",
          toColumnKey: "s0.t0.c0",
          basis: "heading-and-containment",
          brokenReferenceCount: 0,
        },
      ],
    },
  ],
  recordRules: [],
  // F04 (S07): the demo's formulas, live. Jobs Balance and the Customer lookup
  // (through the Customer ID relationship) become computed columns; the four
  // Overview formulas become dashboard values, Balance reading the two SUMs.
  formulas: [
    ["s0.t0.c2", "computed-column", null, "VLOOKUP(B2,Customers!A:B,2,FALSE)", "Jobs!C2:C61", 60, "live", "deterministic", null, "rel:s0.t0.c1", true],
    ["s0.t0.c6", "computed-column", null, "E2-F2", "Jobs!G2:G61", 60, "live", "deterministic", null, null, true],
    ["s5.R3C2", "dashboard-value", "Open jobs", 'COUNTIF(Jobs!D2:D61,"In progress")', "Overview!B3", 1, "live", "deterministic", null, null, true],
    ["s5.R4C2", "dashboard-value", "Quoted total", "SUM(Jobs!E2:E61)", "Overview!B4", 1, "live", "deterministic", null, null, true],
    ["s5.R5C2", "dashboard-value", "Paid total", "SUM(Jobs!F2:F61)", "Overview!B5", 1, "live", "deterministic", null, null, true],
    ["s5.R6C2", "dashboard-value", "Balance", "B4-B5", "Overview!B6", 1, "live", "deterministic", null, null, true],
  ],
  // F04: formulas now live — the three formula items (two columns, the Overview cells) are gone.
  inertCounts: { chart: 1, drawing: 2, "cell-styling": 6 },
  statements: [
    [
      "app-name",
      "app-name",
      "rename-app",
      ["file-name"],
      "accepted",
      "[\"sheaf.inference.v2\",\"app-name\",\"file-name\",\"fieldwork-q3.xlsx\"]",
    ],
    [
      "table-name:s0.t0",
      "table-name",
      "rename-table",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Jobs\",\"JobsTable\",\"declared-table\",\"JobsTable\"]",
    ],
    [
      "header-row:s0.t0",
      "header-row",
      "set-header-row",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Jobs\",\"JobsTable\",\"declared-table\",\"JobsTable\"]",
    ],
    [
      "table-key:s0.t0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Jobs\",\"JobsTable\",\"header-text\",\"Job ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s0.t0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Jobs\",\"JobsTable\",\"header-text\",\"Job ID\",\"distinct-values\"]",
    ],
    [
      "field-name:s0.t0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",0,\"header-text\",\"Job ID\"]",
    ],
    [
      "field-type:s0.t0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",0]",
    ],
    [
      "field-name:s0.t0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",1,\"header-text\",\"Customer ID\"]",
    ],
    [
      "field-type:s0.t0.c1",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",1]",
    ],
    [
      "field-name:s0.t0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",2,\"header-text\",\"Customer\"]",
    ],
    [
      "field-type:s0.t0.c2",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",2]",
    ],
    [
      "formula:s0.t0.c2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Jobs\",\"JobsTable\",2,\"formula-text\",\"VLOOKUP(B2,Customers!A:B,2,FALSE)\"]",
    ],
    [
      "field-name:s0.t0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",3,\"header-text\",\"Status\"]",
    ],
    [
      "field-type:s0.t0.c3",
      "field-type",
      "override-type",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",3,\"validation-rule\",\"list\",\"\",\"Scheduled\",\"In progress\",\"Waiting\",\"Complete\",\"\\\"Scheduled,In progress,Waiting,Complete\\\"\",\"\"]",
    ],
    [
      "enum-options:s0.t0.c3",
      "enum-options",
      "edit-enum-options",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Jobs\",\"JobsTable\",3,\"validation-rule\",\"list\",\"\",\"Scheduled\",\"In progress\",\"Waiting\",\"Complete\",\"\\\"Scheduled,In progress,Waiting,Complete\\\"\",\"\"]",
    ],
    [
      "field-name:s0.t0.c4",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",4,\"header-text\",\"Quoted amount\"]",
    ],
    [
      "field-type:s0.t0.c4",
      "field-type",
      "override-type",
      ["number-format", "value-conflict"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",4,\"number-format\",\"\\\"$\\\"#,##0.00\",\"value-conflict\"]",
    ],
    [
      "field-name:s0.t0.c5",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",5,\"header-text\",\"Paid\"]",
    ],
    [
      "field-type:s0.t0.c5",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",5,\"number-format\",\"\\\"$\\\"#,##0.00\"]",
    ],
    [
      "field-name:s0.t0.c6",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",6,\"header-text\",\"Balance\"]",
    ],
    [
      "field-type:s0.t0.c6",
      "field-type",
      "override-type",
      ["number-format", "value-conflict"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",6,\"number-format\",\"\\\"$\\\"#,##0.00\",\"value-conflict\"]",
    ],
    [
      "formula:s0.t0.c6",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Jobs\",\"JobsTable\",6,\"formula-text\",\"E2-F2\"]",
    ],
    [
      "field-name:s0.t0.c7",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",7,\"header-text\",\"Due date\"]",
    ],
    [
      "field-type:s0.t0.c7",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",7,\"number-format\",\"yyyy-mm-dd\"]",
    ],
    [
      "field-name:s0.t0.c8",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",8,\"header-text\",\"Approved\"]",
    ],
    [
      "field-type:s0.t0.c8",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",8,\"value-pattern\",\"boolean-word\",\"\"]",
    ],
    [
      "field-name:s0.t0.c9",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Jobs\",\"JobsTable\",9,\"header-text\",\"Material\"]",
    ],
    [
      "field-type:s0.t0.c9",
      "field-type",
      "override-type",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Jobs\",\"JobsTable\",9,\"validation-rule\",\"list\",\"\",\"Materials!$A$2:$A$9\",\"Materials!$A$2:$A$9\",\"\"]",
    ],
    [
      "enum-options:s0.t0.c9",
      "enum-options",
      "edit-enum-options",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Jobs\",\"JobsTable\",9,\"validation-rule\",\"list\",\"\",\"Materials!$A$2:$A$9\",\"Materials!$A$2:$A$9\",\"\"]",
    ],
    [
      "table-name:s1.t0",
      "table-name",
      "rename-table",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Customers\",\"CustomersTable\",\"declared-table\",\"CustomersTable\"]",
    ],
    [
      "header-row:s1.t0",
      "header-row",
      "set-header-row",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Customers\",\"CustomersTable\",\"declared-table\",\"CustomersTable\"]",
    ],
    [
      "table-key:s1.t0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Customers\",\"CustomersTable\",\"header-text\",\"Customer ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s1.t0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Customers\",\"CustomersTable\",\"header-text\",\"Name\",\"distinct-values\"]",
    ],
    [
      "field-name:s1.t0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",0,\"header-text\",\"Customer ID\"]",
    ],
    [
      "field-type:s1.t0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",0]",
    ],
    [
      "field-name:s1.t0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",1,\"header-text\",\"Name\"]",
    ],
    [
      "field-type:s1.t0.c1",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",1]",
    ],
    [
      "field-name:s1.t0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",2,\"header-text\",\"Phone\"]",
    ],
    [
      "field-type:s1.t0.c2",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",2,\"value-pattern\",\"telephone-number\",\"\"]",
    ],
    [
      "field-name:s1.t0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Customers\",\"CustomersTable\",3,\"header-text\",\"Email\"]",
    ],
    [
      "field-type:s1.t0.c3",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Customers\",\"CustomersTable\",3,\"value-pattern\",\"email-address\",\"\"]",
    ],
    [
      "table-name:s2.r0",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Crew\",\"r0\",\"sheet-shape\",\"Crew\"]",
    ],
    [
      "header-row:s2.r0",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Crew\",\"r0\",\"header-text\",\"Name · Role · Phone · Crew\"]",
    ],
    [
      "discarded-rows:s2.r0",
      "discarded-rows",
      "set-header-row",
      ["row-shape", "row-shape", "row-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"discarded-rows\",\"Crew\",\"r0\",\"row-shape\",\"row-shape\",\"row-shape\"]",
    ],
    [
      "table-key:s2.r0",
      "table-key",
      "set-key",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Crew\",\"r0\"]",
    ],
    [
      "table-label:s2.r0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Crew\",\"r0\",\"header-text\",\"Name\",\"distinct-values\"]",
    ],
    [
      "field-name:s2.r0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",0,\"header-text\",\"Name\"]",
    ],
    [
      "field-type:s2.r0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",0]",
    ],
    [
      "field-name:s2.r0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",1,\"header-text\",\"Role\"]",
    ],
    [
      "field-type:s2.r0.c1",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "enum-options:s2.r0.c1",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r0\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "field-name:s2.r0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",2,\"header-text\",\"Phone\"]",
    ],
    [
      "field-type:s2.r0.c2",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",2,\"value-pattern\",\"telephone-number\",\"\"]",
    ],
    [
      "field-name:s2.r0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r0\",3,\"header-text\",\"Crew\"]",
    ],
    [
      "field-type:s2.r0.c3",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r0\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "enum-options:s2.r0.c3",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r0\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "table-name:s2.r1",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Crew\",\"r1\",\"sheet-shape\",\"Crew\"]",
    ],
    [
      "header-row:s2.r1",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Crew\",\"r1\",\"header-text\",\"Name · Role · Phone · Crew\"]",
    ],
    [
      "table-merge:s2.r1",
      "table-merge",
      "reject-statement",
      ["matching-headings"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-merge\",\"Crew\",\"r1\",\"matching-headings\",\"Name\",\"Role\",\"Phone\",\"Crew\"]",
    ],
    [
      "table-key:s2.r1",
      "table-key",
      "set-key",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Crew\",\"r1\"]",
    ],
    [
      "table-label:s2.r1",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Crew\",\"r1\",\"header-text\",\"Name\",\"distinct-values\"]",
    ],
    [
      "field-name:s2.r1.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",0,\"header-text\",\"Name\"]",
    ],
    [
      "field-type:s2.r1.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",0]",
    ],
    [
      "field-name:s2.r1.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",1,\"header-text\",\"Role\"]",
    ],
    [
      "field-type:s2.r1.c1",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "enum-options:s2.r1.c1",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r1\",1,\"distinct-values\",\"Apprentice\",\"Driver\",\"Lead\",\"Technician\"]",
    ],
    [
      "field-name:s2.r1.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",2,\"header-text\",\"Phone\"]",
    ],
    [
      "field-type:s2.r1.c2",
      "field-type",
      "override-type",
      ["value-pattern"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",2,\"value-pattern\",\"telephone-number\",\"\"]",
    ],
    [
      "field-name:s2.r1.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Crew\",\"r1\",3,\"header-text\",\"Crew\"]",
    ],
    [
      "field-type:s2.r1.c3",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Crew\",\"r1\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "enum-options:s2.r1.c3",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Crew\",\"r1\",3,\"distinct-values\",\"East\",\"North\",\"South\",\"West\"]",
    ],
    [
      "table-name:s3.t0",
      "table-name",
      "rename-table",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Visits\",\"VisitsTable\",\"declared-table\",\"VisitsTable\"]",
    ],
    [
      "header-row:s3.t0",
      "header-row",
      "set-header-row",
      ["declared-table"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Visits\",\"VisitsTable\",\"declared-table\",\"VisitsTable\"]",
    ],
    [
      "table-key:s3.t0",
      "table-key",
      "set-key",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Visits\",\"VisitsTable\",\"header-text\",\"Visit ID\",\"distinct-values\"]",
    ],
    [
      "table-label:s3.t0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Visits\",\"VisitsTable\",\"header-text\",\"Visit ID\",\"distinct-values\"]",
    ],
    [
      "field-name:s3.t0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",0,\"header-text\",\"Visit ID\"]",
    ],
    [
      "field-type:s3.t0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",0]",
    ],
    [
      "field-name:s3.t0.c1",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",1,\"header-text\",\"Job ID\"]",
    ],
    [
      "field-type:s3.t0.c1",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",1]",
    ],
    [
      "field-name:s3.t0.c2",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",2,\"header-text\",\"Visit date\"]",
    ],
    [
      "field-type:s3.t0.c2",
      "field-type",
      "override-type",
      ["number-format"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",2,\"number-format\",\"yyyy-mm-dd\"]",
    ],
    [
      "field-name:s3.t0.c3",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Visits\",\"VisitsTable\",3,\"header-text\",\"Notes\"]",
    ],
    [
      "field-type:s3.t0.c3",
      "field-type",
      "override-type",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Visits\",\"VisitsTable\",3,\"distinct-values\",\"Follow-up booked\",\"Gate code needed\",\"Measured site\"]",
    ],
    [
      "enum-options:s3.t0.c3",
      "enum-options",
      "edit-enum-options",
      ["distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"enum-options\",\"Visits\",\"VisitsTable\",3,\"distinct-values\",\"Follow-up booked\",\"Gate code needed\",\"Measured site\"]",
    ],
    [
      "sheet-classification:s4.lookup",
      "sheet-classification",
      "reject-statement",
      ["validation-rule"],
      "accepted",
      "[\"sheaf.inference.v2\",\"sheet-classification\",\"Materials\",\"lookup\",\"validation-rule\",\"list\",\"\",\"Materials!$A$2:$A$9\",\"Materials!$A$2:$A$9\",\"\"]",
    ],
    [
      "table-name:s4.r0",
      "table-name",
      "rename-table",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-name\",\"Materials\",\"r0\",\"sheet-shape\",\"Materials\"]",
    ],
    [
      "header-row:s4.r0",
      "header-row",
      "set-header-row",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"header-row\",\"Materials\",\"r0\",\"header-text\",\"Material\"]",
    ],
    [
      "table-key:s4.r0",
      "table-key",
      "set-key",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-key\",\"Materials\",\"r0\"]",
    ],
    [
      "table-label:s4.r0",
      "table-label",
      "set-label",
      ["header-text", "distinct-values"],
      "accepted",
      "[\"sheaf.inference.v2\",\"table-label\",\"Materials\",\"r0\",\"header-text\",\"Material\",\"distinct-values\"]",
    ],
    [
      "field-name:s4.r0.c0",
      "field-name",
      "rename-field",
      ["header-text"],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-name\",\"Materials\",\"r0\",0,\"header-text\",\"Material\"]",
    ],
    [
      "field-type:s4.r0.c0",
      "field-type",
      "override-type",
      [],
      "accepted",
      "[\"sheaf.inference.v2\",\"field-type\",\"Materials\",\"r0\",0]",
    ],
    [
      "sheet-classification:s5.summary",
      "sheet-classification",
      "reject-statement",
      ["sheet-shape"],
      "accepted",
      "[\"sheaf.inference.v2\",\"sheet-classification\",\"Overview\",\"summary\",\"sheet-shape\",\"Overview\"]",
    ],
    [
      "sheet-classification:s5.chart",
      "sheet-classification",
      "reject-statement",
      ["preserved-part"],
      "accepted",
      "[\"sheaf.inference.v2\",\"sheet-classification\",\"Overview\",\"chart\",\"preserved-part\",\"chart\"]",
    ],
    // F04: the Overview summary formulas are dashboard values now, each its own statement.
    [
      "formula:s5.R3C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R3C2\",\"formula-text\",\"COUNTIF(Jobs!D2:D61,\\\"In progress\\\")\"]",
    ],
    [
      "formula:s5.R4C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R4C2\",\"formula-text\",\"SUM(Jobs!E2:E61)\"]",
    ],
    [
      "formula:s5.R5C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R5C2\",\"formula-text\",\"SUM(Jobs!F2:F61)\"]",
    ],
    [
      "formula:s5.R6C2",
      "formula",
      "reject-statement",
      ["formula-text", "formula-outcome"],
      "accepted",
      "[\"sheaf.inference.v2\",\"formula\",\"Overview\",\"R6C2\",\"formula-text\",\"B4-B5\"]",
    ],
    [
      "relationship:rel:s0.t0.c1",
      "relationship",
      "reject-relationship",
      ["lookup-formula"],
      "accepted",
      "[\"sheaf.inference.v2\",\"relationship\",\"Jobs\",\"JobsTable\",1,\"lookup-formula\",\"VLOOKUP\",\"Customers\",\"Customer ID\",\"relationship\"]",
    ],
    [
      "relationship:rel:s3.t0.c1",
      "relationship",
      "reject-relationship",
      ["key-match"],
      "accepted",
      "[\"sheaf.inference.v2\",\"relationship\",\"Visits\",\"VisitsTable\",1,\"key-match\",\"Jobs\",\"Job ID\"]",
    ],
  ],
};

describe("CA-19 — the pinned demo proposal", () => {
  it("proposes exactly this for fieldwork-q3.xlsx with every sheet selected", async () => {
    const proposal = await proposeFixture(DEMO, [0, 1, 2, 3, 4, 5, 6]);
    expect(pinOf(proposal)).toEqual(ALL_SHEETS);
    // F04: 108 → 112, the four Overview dashboard values each gain a statement.
    expect(proposal.statements).toHaveLength(112);
  });

  it("proposes exactly this with Archive 2018 deselected", async () => {
    const proposal = await proposeFixture(DEMO, [0, 1, 2, 3, 4, 5]);
    expect(pinOf(proposal)).toEqual(ARCHIVE_DESELECTED);
    // F04: 95 → 99, the four Overview dashboard values each gain a statement.
    expect(proposal.statements).toHaveLength(99);
  });
});
